# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"
  jobs:
    pre_build:
    - bash ./docs/run_doctest.sh
    - bash ./docs/build_user_guide.sh
    # examples are too expensive for readthedocs.
    # Readthedocs community has 15 min build limits. 
    # examples should be uploaded as pre-built jupyter notebooks 
    # on github.
    - bash ./docs/build_examples.sh no-execute


# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
    - method: pip
      path: .
      extra_requirements: 
        - dev
        - docs
        - numpyro
        - pyabc
        - pymoo
        - interactive
